// Catálogo base. Porciones por persona y por comida, de adulto, del "Manual
// para la aplicación de las Guías Alimentarias para la Población Argentina".
// `estimada` marca las que las GAPA no dan en gramos. Cada usuario lo corrige
// con su `catalogoPropio`; acá sólo se agrega lo que sirve a cualquiera.
import { EntradaCatalogo } from './catalogo';

const CARNE = { grupo: 'carnesHuevos', unidad: 'g', porcion: 150, estimada: true } as const;
const CEREAL = { grupo: 'feculentos', unidad: 'g', porcion: 50, estimada: true } as const;
const LEGUMBRE = { grupo: 'feculentos', unidad: 'g', porcion: 125, legumbre: true } as const;
const FRUTA = { grupo: 'frutas', unidad: 'unidad', porcion: 1 } as const;
const QUESO = { grupo: 'lacteos', unidad: 'g', porcion: 30, estimada: true } as const;
const HIERBA = { grupo: 'condimentos', unidad: 'cda', planta: true } as const;
const CONDIMENTO = { grupo: 'condimentos', unidad: 'cdita' } as const;

export const CATALOGO: readonly EntradaCatalogo[] = [
  // Hortalizas: sin porción; las cubre el "medio plato" del resumen.
  { nombre: 'acelga', sinonimos: ['acelga o espinaca'], grupo: 'hortalizas', unidad: 'atado' },
  { nombre: 'ajo', sinonimos: ['diente de ajo'], grupo: 'hortalizas', unidad: 'diente' },
  { nombre: 'apio', sinonimos: ['blanco de apio'], grupo: 'hortalizas', unidad: 'rama' },
  { nombre: 'berenjena', grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'berro', grupo: 'hortalizas', unidad: 'atado' },
  { nombre: 'brócoli', sinonimos: ['brocolis'], grupo: 'hortalizas', unidad: 'unidad' },
  {
    nombre: 'brotes de soja',
    sinonimos: ['brotes de arveja', 'brotes de arveja o soja'],
    grupo: 'hortalizas',
    unidad: 'g',
  },
  { nombre: 'calabaza', sinonimos: ['zapallo anco'], grupo: 'hortalizas', unidad: 'g' },
  { nombre: 'cebolla', grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'cebolla de verdeo', sinonimos: ['verdeo', 'cebollita de verdeo'], grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'cebolla morada', grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'champignones', sinonimos: ['hongos', 'champiñones'], grupo: 'hortalizas', unidad: 'g' },
  { nombre: 'chauchas', grupo: 'hortalizas', unidad: 'g' },
  { nombre: 'coliflor', grupo: 'hortalizas', unidad: 'unidad' },
  {
    nombre: 'corazones de alcaucil',
    sinonimos: ['alcaucil', 'alcauciles'],
    grupo: 'hortalizas',
    unidad: 'unidad',
  },
  { nombre: 'espinaca', sinonimos: ['espinaca o acelga'], grupo: 'hortalizas', unidad: 'atado' },
  { nombre: 'hojas verdes', sinonimos: ['mix de hojas verdes'], grupo: 'hortalizas', unidad: 'plato' },
  { nombre: 'lechuga', sinonimos: ['lechuga mantecosa', 'lechuga criolla'], grupo: 'hortalizas', unidad: 'unidad' },
  {
    nombre: 'morrón',
    sinonimos: ['morron rojo', 'morron verde', 'pimiento', 'aji', 'aji verde', 'aji morron'],
    grupo: 'hortalizas',
    unidad: 'unidad',
  },
  { nombre: 'palmitos', grupo: 'hortalizas', unidad: 'lata' },
  { nombre: 'pepino', grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'puerro', grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'rabanitos', sinonimos: ['rabanito', 'rabanos'], grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'radicheta', grupo: 'hortalizas', unidad: 'atado' },
  { nombre: 'remolacha', grupo: 'hortalizas', unidad: 'unidad' },
  { nombre: 'repollo', sinonimos: ['repollo blanco'], grupo: 'hortalizas', unidad: 'taza' },
  { nombre: 'repollo colorado', grupo: 'hortalizas', unidad: 'taza' },
  { nombre: 'rúcula', grupo: 'hortalizas', unidad: 'atado' },
  {
    nombre: 'tomate',
    sinonimos: [
      'tomate perita',
      'tomates cherry',
      'tomate cherry',
      'tomate triturado',
      'tomate pelado',
      'pure de tomate',
      'pulpa de tomate',
      'tomates perita',
    ],
    grupo: 'hortalizas',
    unidad: 'unidad',
  },
  { nombre: 'zanahoria', sinonimos: ['zanahoria rallada'], grupo: 'hortalizas', unidad: 'unidad' },
  {
    nombre: 'zapallito',
    sinonimos: ['zapallito redondo', 'zapallito verde'],
    grupo: 'hortalizas',
    unidad: 'unidad',
  },
  { nombre: 'zapallo', grupo: 'hortalizas', unidad: 'g' },
  { nombre: 'zucchini', sinonimos: ['zuccini', 'zuchini', 'zapallito largo'], grupo: 'hortalizas', unidad: 'unidad' },

  // Frutas.
  { nombre: 'ananá', sinonimos: ['anana en lata'], ...FRUTA },
  { nombre: 'arándanos', grupo: 'frutas', unidad: 'taza', porcion: 1 },
  { nombre: 'banana', ...FRUTA },
  { nombre: 'ciruela', ...FRUTA },
  { nombre: 'damasco', sinonimos: ['damascos secos'], ...FRUTA },
  { nombre: 'dátil', ...FRUTA },
  { nombre: 'durazno', sinonimos: ['durazno en lata'], ...FRUTA },
  { nombre: 'frutillas', sinonimos: ['frutilla'], grupo: 'frutas', unidad: 'taza', porcion: 1 },
  { nombre: 'kiwi', ...FRUTA },
  { nombre: 'limón', sinonimos: ['jugo de limon'], grupo: 'frutas', unidad: 'unidad' },
  { nombre: 'mandarina', ...FRUTA },
  { nombre: 'manzana', sinonimos: ['manzana verde', 'manzana roja'], ...FRUTA },
  { nombre: 'naranja', ...FRUTA },
  { nombre: 'palta', grupo: 'frutas', unidad: 'unidad' },
  { nombre: 'pera', ...FRUTA },
  { nombre: 'pomelo', ...FRUTA },
  { nombre: 'uvas', ...FRUTA },

  // Feculentos: legumbres, cereales, papa, batata, choclo.
  { nombre: 'arroz', sinonimos: ['arroz blanco'], ...CEREAL },
  { nombre: 'arroz integral', ...CEREAL },
  {
    nombre: 'avena',
    sinonimos: ['avena arrollada', 'harina de avena', 'copos de avena'],
    grupo: 'feculentos',
    unidad: 'g',
  },
  { nombre: 'fideos', sinonimos: ['spaghetti', 'tallarines', 'pasta', 'fideos secos', 'mostachol'], ...CEREAL },
  { nombre: 'polenta', ...CEREAL },
  { nombre: 'quinoa', ...CEREAL },
  { nombre: 'maicena', sinonimos: ['almidon de maiz'], grupo: 'feculentos', unidad: 'cda' },
  { nombre: 'papa', grupo: 'feculentos', unidad: 'unidad', porcion: 1 },
  { nombre: 'batata', sinonimos: ['boniato'], grupo: 'feculentos', unidad: 'unidad', porcion: 1 },
  { nombre: 'choclo', sinonimos: ['choclo desgranado', 'maiz'], grupo: 'feculentos', unidad: 'unidad', porcion: 0.5 },
  { nombre: 'mandioca', grupo: 'feculentos', unidad: 'unidad', porcion: 0.5 },
  { nombre: 'arvejas', sinonimos: ['arveja'], ...LEGUMBRE },
  { nombre: 'garbanzos', sinonimos: ['garbanzos cocidos'], ...LEGUMBRE },
  { nombre: 'harina de garbanzos', grupo: 'feculentos', unidad: 'g', legumbre: true },
  { nombre: 'lentejas', sinonimos: ['lentejas cocidas'], ...LEGUMBRE },
  { nombre: 'porotos', sinonimos: ['porotos cocidos', 'porotos blancos', 'porotos alubia'], ...LEGUMBRE },
  { nombre: 'porotos aduki', ...LEGUMBRE },
  { nombre: 'porotos negros', ...LEGUMBRE },

  // Pan y masas.
  { nombre: 'pan', sinonimos: ['pan frances', 'mignon'], grupo: 'pan', unidad: 'g', porcion: 60 },
  { nombre: 'pan integral', grupo: 'pan', unidad: 'g', porcion: 60 },
  { nombre: 'pan árabe', grupo: 'pan', unidad: 'g', porcion: 60, estimada: true },
  { nombre: 'pan rallado', grupo: 'pan', unidad: 'g' },
  { nombre: 'tapas de tarta', sinonimos: ['tapa de tarta'], grupo: 'pan', unidad: 'unidad' },
  { nombre: 'tapas de empanada', sinonimos: ['tapa de empanada'], grupo: 'pan', unidad: 'unidad' },
  { nombre: 'tortillas para wrap', sinonimos: ['tortilla de trigo', 'rapiditas'], grupo: 'pan', unidad: 'unidad' },
  { nombre: 'tostadas de arroz', sinonimos: ['galletas de arroz'], grupo: 'pan', unidad: 'unidad' },
  { nombre: 'harina de almendras', grupo: 'aceitesSemillas', unidad: 'g' },

  // Lácteos.
  { nombre: 'leche', sinonimos: ['leche descremada', 'leche entera'], grupo: 'lacteos', unidad: 'taza', porcion: 1 },
  {
    nombre: 'yogur',
    sinonimos: ['yogur natural', 'yogur descremado', 'yogurt'],
    grupo: 'lacteos',
    unidad: 'g',
    porcion: 200,
  },
  { nombre: 'queso', ...QUESO },
  { nombre: 'mozzarella', sinonimos: ['muzza', 'muzzarella'], ...QUESO },
  { nombre: 'queso fresco', sinonimos: ['queso fresco descremado', 'queso cremoso'], ...QUESO },
  { nombre: 'queso port salut', sinonimos: ['port salut'], ...QUESO },
  { nombre: 'queso rallado', sinonimos: ['queso de rallar'], grupo: 'lacteos', unidad: 'cda', porcion: 3 },
  {
    nombre: 'queso blanco',
    sinonimos: ['queso blanco descremado', 'queso crema', 'queso untable'],
    grupo: 'lacteos',
    unidad: 'cda',
    porcion: 6,
  },
  { nombre: 'ricota', sinonimos: ['ricota descremada'], grupo: 'lacteos', unidad: 'cda', porcion: 6, estimada: true },
  { nombre: 'crema de leche', sinonimos: ['crema de leche light'], grupo: 'lacteos', unidad: 'ml' },

  // Carnes y huevos.
  {
    nombre: 'carne vacuna',
    sinonimos: ['carne', 'carne magra', 'carne vacuna magra', 'churrasco', 'churrasco magro', 'bife', 'carne al horno'],
    ...CARNE,
  },
  { nombre: 'carne picada', sinonimos: ['carne picada magra', 'carne picada muy magra'], ...CARNE },
  { nombre: 'lomo', sinonimos: ['medallon de lomo', 'medallones de lomo'], ...CARNE },
  {
    nombre: 'pechuga de pollo',
    sinonimos: ['pechuga', 'bife de pechuga', 'pollo', 'pollo (cuarto)', 'pollo cocido', 'pollo hervido'],
    ...CARNE,
  },
  { nombre: 'cerdo', sinonimos: ['lomo de cerdo', 'bondiola', 'carre de cerdo'], ...CARNE },
  {
    nombre: 'pescado',
    sinonimos: [
      'filet de pescado',
      'fillet',
      'fillet (o medallon)',
      'filet de merluza',
      'merluza',
      'filet de brotola',
      'brotola',
      'milanesa de pescado',
      'medallon de merluza',
    ],
    ...CARNE,
  },
  { nombre: 'atún', sinonimos: ['atun al natural', 'atun en lata'], ...CARNE },
  { nombre: 'huevo', grupo: 'carnesHuevos', unidad: 'unidad', porcion: 1 },
  { nombre: 'clara', sinonimos: ['clara de huevo'], grupo: 'carnesHuevos', unidad: 'unidad' },

  // Aceites, semillas y frutas secas.
  {
    nombre: 'aceite de oliva',
    sinonimos: ['aceite', 'aceite de girasol', 'aceite de oliva o chia'],
    grupo: 'aceitesSemillas',
    unidad: 'cda',
    porcion: 1,
    planta: false,
  },
  { nombre: 'aceite de coco', grupo: 'aceitesSemillas', unidad: 'cda', porcion: 1, planta: false },
  {
    nombre: 'aceitunas',
    sinonimos: ['aceitunas negras', 'aceitunas verdes'],
    grupo: 'aceitesSemillas',
    unidad: 'unidad',
  },
  { nombre: 'semillas de lino', sinonimos: ['lino'], grupo: 'aceitesSemillas', unidad: 'cda', porcion: 1 },
  { nombre: 'semillas de chía', sinonimos: ['chia'], grupo: 'aceitesSemillas', unidad: 'cda', porcion: 1 },
  { nombre: 'semillas de girasol', grupo: 'aceitesSemillas', unidad: 'cda', porcion: 1 },
  { nombre: 'semillas de sésamo', sinonimos: ['sesamo'], grupo: 'aceitesSemillas', unidad: 'cda', porcion: 1 },
  { nombre: 'nueces', grupo: 'aceitesSemillas', unidad: 'puñado', porcion: 1 },
  { nombre: 'almendras', grupo: 'aceitesSemillas', unidad: 'puñado', porcion: 1 },
  { nombre: 'castañas de cajú', grupo: 'aceitesSemillas', unidad: 'puñado', porcion: 1 },
  { nombre: 'maní', sinonimos: ['pasta de mani'], grupo: 'aceitesSemillas', unidad: 'puñado', porcion: 1 },
  {
    nombre: 'mayonesa',
    sinonimos: ['mayonesa sin colesterol', 'mayonesa light', 'mayonesa diet'],
    grupo: 'aceitesSemillas',
    unidad: 'cda',
    planta: false,
  },
  { nombre: 'salsa golf', sinonimos: ['salsa golf diet'], grupo: 'aceitesSemillas', unidad: 'cda', planta: false },

  // Condimentos. Las hierbas frescas cuentan como planta.
  { nombre: 'perejil', ...HIERBA },
  { nombre: 'albahaca', ...HIERBA },
  { nombre: 'cilantro', ...HIERBA },
  { nombre: 'ciboulette', ...HIERBA },
  { nombre: 'menta', ...HIERBA },
  { nombre: 'sal', ...CONDIMENTO },
  { nombre: 'pimienta', ...CONDIMENTO },
  { nombre: 'orégano', ...CONDIMENTO },
  { nombre: 'laurel', sinonimos: ['hoja de laurel', 'hojas de laurel'], grupo: 'condimentos', unidad: 'hoja' },
  { nombre: 'pimentón', sinonimos: ['pimenton dulce'], ...CONDIMENTO },
  { nombre: 'canela', ...CONDIMENTO },
  { nombre: 'comino', ...CONDIMENTO },
  { nombre: 'nuez moscada', ...CONDIMENTO },
  { nombre: 'mostaza', ...CONDIMENTO },
  { nombre: 'vinagre', ...CONDIMENTO },
  { nombre: 'salsa de soja', sinonimos: ['salsa de soya'], ...CONDIMENTO },
  { nombre: 'caldo', sinonimos: ['caldo de verduras', 'caldo desgrasado'], grupo: 'condimentos', unidad: 'taza' },
  { nombre: 'vino blanco', grupo: 'condimentos', unidad: 'vaso' },
  { nombre: 'polvo de hornear', ...CONDIMENTO },
  { nombre: 'esencia de vainilla', sinonimos: ['escencia de vainilla'], ...CONDIMENTO },
  { nombre: 'stevia', ...CONDIMENTO },
];

export const TAGS_BASE: readonly string[] = [
  'desayuno',
  'almuerzo',
  'cena',
  'colación',
  'postre',
  'ensalada',
  'guarnición',
  'sopa',
  'tarta',
  'guiso',
  'salteado',
  'horno',
  'vegetariano',
  'vegano',
  'sin gluten',
  'rápido',
  'fácil',
  'alto_proteina',
];
